Repository milieuinfo/webcomponent-vl-ui-pill, pull requests merged in 2019-09, with the labels that each got.

#16 UIG-218
  vl-pill.src.js
Labels: maintenance

#17 Update link naar demo
  vl-pill.src.js
Labels: maintenance

#18 Automatic commit via update script
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  package-lock.json
  package.json
Labels: maintenance

#8 Update dependency np to v3.1.0
  package-lock.json
  package.json
Labels: dependencies, renovate

#23 Update dependency vl-ui-core to v1.4.6
  package-lock.json
  package.json
Labels: dependencies

#22 Update dependency replace to v1.1.1
  package-lock.json
  package.json
Labels: dependencies

#21 Update dependency @govflanders/vl-ui-util to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#20 Update dependency @govflanders/vl-ui-pill to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#19 Update dependency @govflanders/vl-ui-core to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#24 Update dependency vl-ui-core to v1.4.7
  package-lock.json
  package.json
Labels: dependencies

#28 Automatic commit via update script
  demo/demo.css
  package-lock.json
  style.css
Labels: maintenance

#30 Update and install latest util
  .github/ISSUE_TEMPLATE/task.md
  bamboo-specs/bamboo.yml
  demo/demo.css
  package-lock.json
  package.json
  style.css
Labels: maintenance

#33 Update vl-ui-util
  CODEOWNERS
  demo/demo.css
  package-lock.json
  package.json
  style.css
Labels: maintenance
