Repository milieuinfo/webcomponent-vl-ui-pill, pull requests merged in 2020-01, with the labels that each got.

#42 Update vl-ui-util
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.js
  package-lock.json
  package.json
  style.css
  test/docker-compose.yml
  wct.docker.conf.json
  wct.local.conf.json
Labels: maintenance

#43 Fix testopzet
  .mocharc.js
  index.js
  package-lock.json
  package.json
  test/e2e/pages/vl-pill.page.js
  test/e2e/pill.test.js
  test/unit/vl-pill.test.html
  test/wct.docker.conf.json
Labels: chore

#44 Fix testopzet
  package-lock.json
  package.json
Labels: bugfix

#45 Fix testopzet
  .gitignore
  test/e2e/components/vl-pill.js
Labels: bugfix

#48 Verwijder pretest fase (installeren chromedriver). Deze komt via vl-ui-util binnen
  package.json
Labels: chore

#46 Overbodig NPM release import scripts verwijderd
  package.json
  style.css
  vl-pill.js
Labels: maintenance

#47 Update vl-ui-util
  demo/demo.css
  package-lock.json
  package.json
  style.css
  test/docker-compose.yml
Labels: maintenance

#49 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  style.css
  test/docker-compose.yml
Labels: maintenance

#50 Update vl-ui-util
  bamboo-specs/bamboo.yml
  docker-compose-release.yml
  package-lock.json
  package.json
Labels: maintenance
